name: Convert to PDF

on:
  push:
    branches:
      - master
    paths:
      - '**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: README.md
          output_dir: pdfs
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: pdfs/README.pdf
          compression-level: 0
